# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/vendor/cirrus/audio/dlkm/include

cirrus_wm_adsp-objs = wm_adsp.o
obj-m += cirrus_wm_adsp.o

ifneq ($(filter m y,$(CONFIG_SND_SOC_CS35L41_I2C)),)
cirrus_cs35l41-objs = cs35l41.o cs35l41-tables.o cs35l41-i2c.o
else
cirrus_cs35l41-objs = cs35l41.o cs35l41-tables.o cs35l41-spi.o
endif
obj-m += cirrus_cs35l41.o
